dist: xenial

language: python
python:
  - "2.7"
  - "3.8"

addons:
  apt:
    packages:
      - git
      - curl
      - wget

before_install:
  - echo "before"

install:
  - echo "install"

script:
  - make gfw2pac

after_success:
  - echo "build after"
