#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org / https://spacevim.org/cn/
# License: GPLv3
#=============================================================================

# 所有的 SpaceVim 选项都列在 [options] 之下
[options]
    # 设置 SpaceVim 主题及背景，默认的主题是 gruvbox，如果你需要使用更
    # 多的主题，你可以载入 colorscheme 模块 https://spacevim.org/cn/layers/colorscheme/
    colorscheme = "palenight"
    # 背景可以取值 "dark" 或 "light"x`x
    colorscheme_bg = "dark"
    # 启用/禁用终端真色，在目前大多数终端下都是支持真色的，当然也有
    # 一小部分终端不支持真色，如果你的 SpaceVim 颜色看上去比较怪异
    # 可以禁用终端真色，将下面的值设为 false
    enable_guicolors = true
    # 设置状态栏上分割符号形状，如果字体安装失败，可以将值设为 "nil" 以
    # 禁用分割符号，默认为箭头 "arrow"
    statusline_separator = "nil"
    statusline_iseparator = "bar"
    # 设置顶部标签列表序号类型，有以下五种类型，分别是 0 - 4
    # 0: 1 ➛ ➊
    # 1: 1 ➛ ➀
    # 2: 1 ➛ ⓵
    # 3: 1 ➛ ¹
    # 4: 1 ➛ 1
    buffer_index_type = 4
    # 显示/隐藏顶部标签栏上的文件类型图标，这一图标需要安装 nerd fonts，
    # 如果未能成功安装这一字体，可以隐藏图标
    enable_tabline_filetype_icon = true
    # 是否在状态栏上显示当前模式，默认情况下，不显示 Normal/Insert 等
    # 字样，只以颜色区分当前模式
    enable_statusline_mode = false
    # 自定义代码补全
    # snippet_engine = "ultisnips"
    # 默认情况下文件树是在窗口的右边打开
    filetree_direction = "left"
    spacevim_enable_vimfiler_filetypeicon = true

    autocomplete_method = "coc"
    # Enable/Disable show mode on statusline
    enable_statusline_mode = true
    # left sections of statusline
    statusline_separator = "arrow"
    # Set the statusline separators of inactive statusline
    statusline_inactive_separator = "bar"
    statusline_left_sections = [
       'winnr',
       'major mode',
       'filename',
       # 'fileformat',
       'minor mode lighters',
       'version control info',
       'search status'
    ]
    # right sections of statusline
    statusline_right_sections = [
       'cursorpos',
       'percentage',
       'input method',
       'date',
       'time'
    ]
    lint_on_the_fly = true
    go_rename_command = 'gopls'
    go_metalinter_command='golangci-lint'
    go_metalinter_autosave = true
    go_metalinter_enabeld = ['deadcode', 'errcheck', 'gosimple', 'govet', 'staticcheck', 'typecheck', 'unused', 'varcheck']


# SpaceVim 模块设置，主要包括启用/禁用模块

# 启用 autocomplete 模块，启用模块时，可以列出一些模块选项，并赋值，
# 关于模块的选项，请阅读各个模块的文档
[[layers]]
    # https://spacevim.org/cn/layers/autocomplete/
    name = "autocomplete"
    auto-completion-return-key-behavior = "complete"
    auto-completion-tab-key-behavior = "smart" # cycle, smart
    auto_completion_delay = 200
    auto_completion_complete_with_key_sequence = "nil"
    auto_completion_complete_with_key_sequence_delay = 0.1

# 禁用 shell 模块，禁用模块时，需要加入 enable = false
[[layers]]
    name = "shell"
    enable = false
    default_position = "top"
    default_height = 30

# go ide
[[layers]]
    name = "lang#go"
    format_on_save = true

[[layers]]
    name = "lang#python"

[[layers]]
  name = "lang#javascript"

[[layers]]
  name = "lang#lua"

[[layers]]
  name = "lang#dockerfile"

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "test"
  [layers.override_config]
    go_runner = "delve"

[[layers]]
    name = "format"

[[layers]]
    name = "checkers"

[[layers]]
   name = "debug"

[[layers]]
    name = "colorscheme"

[[layers]]
    name = "ui"
    enable_scrollbar = true

[[layers]]
    # 模块提供了一个高度定制的状态栏
    name = "core#statusline"

[[layers]]
    # 搜索结果展示
    name = "incsearch"

[[layers]]
  name = 'edit'
  autosave_timeout = 10000
  autosave_location = '~/.cache/spacevim/backup/'
  name = "VersionControl"

[[layers]]
  name = "git"
  git-plugin = "fugitive"

[[layers]]
  name = "fzf"

[[layers]]
  name="tools"

[[layers]]
  name = "default"

[[layers]]
  name="core"

[[layers]]
  name = "tmux"

[[layers]]
  name="core#tabline"

# 添加自定义插件 lilydjwg/colorizer
[[custom_plugins]]
    repo = "lilydjwg/colorizer"
    merged = false

[[custom_plugins]]
    repo = "junegunn/vader.vim"
    merged = false

[[custom_plugins]]
    repo = 'joshdick/onedark.vim'
    merged = false